/**
 * Todos os textos do app vivem aqui, em português do Brasil.
 * Regra: nenhum componente escreve texto de interface direto no JSX —
 * assim a revisão de tom e a busca por qualquer frase acontecem num lugar só.
 */
export const textos = {
  app: {
    nome: 'Mozii',
    slogan: 'vocês, em um só lugar',
  },

  comuns: {
    salvar: 'Salvar',
    cancelar: 'Cancelar',
    confirmar: 'Confirmar',
    carregando: 'Carregando…',
    erroInesperado: 'Algo deu errado. Tenta de novo?',
  },

  entrar: {
    titulo: 'Que bom te ver',
    email: 'E-mail',
    senha: 'Senha',
    botao: 'Entrar',
    entrando: 'Entrando…',
    semConta: 'Ainda não tem conta?',
    linkCadastro: 'Criar conta',
    credenciaisInvalidas: 'E-mail ou senha incorretos.',
    emailNaoConfirmado: 'Seu e-mail ainda não foi confirmado. Olha na caixa de entrada?',
  },

  cadastro: {
    titulo: 'Criar sua conta',
    nome: 'Seu nome',
    nomeDica: 'Como seu par te chama?',
    email: 'E-mail',
    senha: 'Senha (mínimo 8 caracteres)',
    botao: 'Criar conta',
    criando: 'Criando…',
    jaTemConta: 'Já tem conta?',
    linkEntrar: 'Entrar',
    emailJaExiste: 'Este e-mail já tem conta. Tenta entrar?',
  },

  confirmarEmail: {
    titulo: 'Confirma seu e-mail 💌',
    explicacaoAntes: 'Enviamos um link para',
    explicacaoDepois: 'Toca nele para ativar sua conta — depois é só entrar.',
    reenviar: 'Reenviar e-mail',
    reenviado: 'E-mail reenviado!',
    jaConfirmei: 'Já confirmei, entrar',
    linkInvalidoTitulo: 'Esse link não deu certo',
    linkInvalidoDescricao:
      'Ele pode ter expirado ou já ter sido usado. Entre para pedir outro link.',
    voltarParaEntrar: 'Ir para entrar',
  },

  parear: {
    titulo: 'Falta uma pessoa',
    subtitulo: 'O Mozii é feito para vocês dois. Crie o espaço ou entre no do seu par.',
    criarTitulo: 'Começar o nosso espaço',
    criarBotao: 'Criar espaço do casal',
    criando: 'Criando…',
    codigoCriadoTitulo: 'Espaço criado!',
    codigoCriadoDica: 'Mostre este código para seu par entrar:',
    irParaApp: 'Ir para o Mozii',
    entrarTitulo: 'Meu par já criou',
    entrarRotulo: 'Código de convite',
    entrarBotao: 'Entrar no espaço',
    entrando: 'Entrando…',
    codigoInvalido: 'Código inválido. Confere com seu par?',
    ou: 'ou',
  },

  mural: {
    titulo: 'Mural',
    juntos: (nomes: string[]) => nomes.join(' ♥ '),
    esperandoPar: 'Seu par ainda não entrou — o código de convite está nos Ajustes.',
    vazio: 'O Mural de vocês começa aqui 💜',
    vazioDica: 'Publiquem a primeira memória de cinema.',
    vazioAcao: 'Publicar algo',
    carregarMais: 'Carregar mais',
  },

  novo: {
    titulo: 'Nova publicação',
    dicaTexto: 'Escreve algo para vocês…',
    foto: 'Foto',
    removerFoto: 'Remover foto',
    avaliarFilme: 'Avaliar um filme',
    trocarFilme: 'Trocar filme',
    removerFilme: 'Remover filme',
    notaRotulo: 'Sua nota',
    publicar: 'Publicar',
    publicando: 'Publicando…',
    faltaConteudo: 'Escreva algo, escolha uma foto ou avalie um filme.',
    faltaNota: 'Toque nas estrelas para dar a nota.',
    avaliacaoExistente: 'Você já avaliou este filme. Edite sua avaliação.',
  },

  publicacao: {
    titulo: 'Publicação',
    comentarios: 'Comentários',
    comentarDica: 'Comentar…',
    enviar: 'Enviar',
    excluir: 'Excluir publicação',
    excluirConfirmar: 'Excluir esta publicação?',
    excluirExplicacao: 'Ela some do Mural para vocês dois.',
    editar: 'Editar avaliação',
    naoEncontrada: 'Publicação não encontrada.',
  },

  atividade: {
    adicionou: (nome: string, filme: string, lista: string) =>
      `${nome} adicionou ${filme} à lista ${lista}`,
    assistiu: (nome: string, filme: string) => `${nome} marcou ${filme} como assistido`,
    agendou: (nome: string, filme: string, quando: string) =>
      `${nome} agendou ${filme} para ${quando}`,
  },

  sessao: {
    agendarBotao: 'Agendar sessão',
    modalTitulo: 'Agendar sessão',
    quandoRotulo: 'Quando?',
    observacaoDica: 'Combinados (ex.: leva pipoca doce) — opcional',
    agendar: 'Agendar',
    agendando: 'Agendando…',
    agendadaAviso: 'Sessão agendada 🍿',
    agendarDoSorteio: 'Agendar este!',
    cartaoTitulo: 'Próxima sessão',
    passadasTitulo: 'Sessões passadas',
    comoFoi: 'E aí, como foi? 🍿',
    comoFoiCurto: 'Como foi?',
    concluida: 'assistida',
    avaliarFilme: 'Avaliar filme',
    soMarcar: 'Só marcar como assistida',
    reagendar: 'Reagendar',
    novaDataRotulo: 'Nova data e horário',
    cancelar: 'Cancelar sessão',
    cancelarConfirmar: 'Cancelar esta sessão?',
    cancelarExplicacao: 'O agendamento some para vocês dois; o filme continua nas listas.',
    calendario: 'Calendário',
    descricaoIcs: 'Sessão de cinema do casal, marcada no Mozii 💜',
    gestaoAtalho: 'Sessões',
    gestaoTitulo: 'Sessões agendadas',
    programacao: 'Na programação',
    gestaoResumo: (quantidade: number) =>
      quantidade === 1 ? '1 sessão para gerenciar' : `${quantidade} sessões para gerenciar`,
    proximasTitulo: 'Próximas sessões',
    aguardandoTitulo: 'Aguardando vocês',
    aguardandoDescricao: 'O horário passou. Marque como assistida, avalie ou cancele.',
    vazioTitulo: 'Nenhuma sessão agendada',
    vazioDescricao: 'Quando vocês marcarem um filme, ele aparece aqui para gerenciar.',
    buscarFilme: 'Buscar um filme',
    erroCarregar: 'Não foi possível carregar as sessões',
    erroCarregarDica: 'Confira a conexão e tente abrir esta tela novamente.',
  },

  compartilhar: {
    titulo: 'Compartilhar nos Stories',
    botaoAbrir: 'Compartilhar',
    tema: 'Tema',
    compartilhar: 'Compartilhar',
    baixar: 'Baixar imagem',
    gerando: 'Gerando o cartão…',
    erro: 'Não consegui gerar a imagem. Tenta de novo?',
  },

  reacoes: {
    curtir: 'Curtir',
    descurtir: 'Descurtir',
    comentar: 'Comentar',
  },

  navegacao: {
    mural: 'Mural',
    cinema: 'Cinema',
    momentos: 'Momentos',
    perfil: 'Perfil',
    ajustes: 'Ajustes',
  },

  momentos: {
    titulo: 'Momentos',
    subtitulo: 'o diário de vocês',
    vazio: 'O diário de vocês começa aqui. Registrem a primeira memória!',
    nova: 'Nova memória',
    legendaDica: 'O que aconteceu?',
    dataRotulo: 'Quando foi?',
    fotosRotulo: 'Fotos',
    salvar: 'Guardar memória',
    salvando: 'Guardando…',
    faltaConteudo: 'Uma memória precisa de legenda ou de pelo menos uma foto.',
    excluir: 'Excluir memória',
    excluirConfirmar: 'Excluir esta memória?',
    excluirExplicacao: 'A memória, as fotos e o espelho no Mural somem para vocês dois.',
    hoje: 'Hoje',
    ontem: 'Ontem',
  },

  perfil: {
    titulo: 'Perfil',
    stats: {
      avaliados: 'filmes avaliados',
      media: 'nota média',
      esteAno: 'este ano',
      listas: 'listas criadas',
    },
    favoritos: 'Favoritos',
    favoritosDica: 'Toque num espaço vazio para escolher um favorito.',
    removerFavorito: 'Remover dos favoritos',
    avaliacoesRecentes: 'Avaliações recentes',
    semAvaliacoes: 'Nenhuma avaliação ainda.',
    histograma: 'Distribuição das notas',
    pegadas: 'Minhas Pegadas',
    pegadasDe: (nome: string) => `Pegadas de ${nome}`,
  },

  cinema: {
    titulo: 'Cinema',
    abaBuscar: 'Buscar',
    abaListas: 'Listas',
    buscarDica: 'Busque um filme…',
    buscando: 'Buscando…',
    semResultados: 'Nada encontrado com esse nome.',
    novaListaDica: 'Nome da nova lista',
    novaListaBotao: 'Criar lista',
    semListas: 'Vocês ainda não têm listas. Que tal uma "Para ver juntos"?',
  },

  filme: {
    adicionarALista: 'Adicionar à lista',
    avaliar: 'Avaliar filme',
    editarAvaliacao: 'Editar avaliação',
    avaliacoes: 'Avaliações',
    semAvaliacoes: 'Ainda não há avaliações deste filme.',
    ondeAssistir: 'Onde assistir',
    aluguel: 'Para alugar',
    semProvedores: 'Sem streaming no Brasil por enquanto.',
    verNoJustWatch: 'Ver todas as opções no JustWatch',
    duracao: (minutos: number) => `${Math.floor(minutos / 60)}h ${minutos % 60}min`,
    naoEncontrado: 'Filme não encontrado.',
  },

  folhaLista: {
    titulo: 'Em qual lista?',
    jaEsta: 'já está',
    adicionado: 'Adicionado!',
  },

  lista: {
    progresso: (assistidos: number, total: number) => `${assistidos} de ${total} assistidos`,
    vazia: 'Lista vazia — busque um filme para adicionar.',
    adicionarFilme: 'Adicionar filme',
    adicionadoPor: (nome: string) => `por ${nome}`,
    marcarAssistido: 'Marcar como assistido',
    desmarcarAssistido: 'Desmarcar assistido',
    removerItem: 'Remover da lista',
    excluir: 'Excluir lista',
    excluirConfirmar: 'Excluir esta lista?',
    excluirExplicacao: 'A lista e os itens dela somem para vocês dois.',
  },

  sorteio: {
    botao: 'O que ver hoje',
    titulo: 'O que ver hoje',
    rolando: 'Sorteando…',
    verFilme: 'Ver o filme',
    sortearDeNovo: 'Sortear de novo',
    todosAssistidos: 'Vocês já viram tudo desta lista! 🎉',
  },

  ajustes: {
    titulo: 'Ajustes',
    nomeRotulo: 'Seu nome',
    nomeSalvo: 'Nome salvo!',
    avatarRotulo: 'Trocar foto de perfil',
    avatarSalvo: 'Foto atualizada!',
    casalTitulo: 'Nosso espaço',
    codigoConvite: 'Código de convite',
    codigoDica: 'Seu par usa este código para entrar.',
    membros: 'Quem está aqui',
    aniversarioRotulo: 'Data do nosso aniversário',
    aniversarioDica: 'Aparece como marco na linha do tempo dos Momentos.',
    sairConta: 'Sair da conta',
    zonaPerigo: 'Zona de perigo',
    sairCasal: 'Sair do espaço',
    sairCasalExplicacao:
      'Você sai do espaço do casal; suas publicações continuam lá. Dá para voltar com o código.',
    sairCasalConfirmar: 'Sair do espaço do casal?',
    excluirConta: 'Excluir minha conta',
    excluirContaExplicacao:
      'Sua conta e tudo que você criou somem de verdade após 30 minutos. Entrar de novo dentro desse prazo cancela a exclusão.',
    excluirContaConfirmar: 'Excluir sua conta de verdade?',
  },

  notificacoes: {
    titulo: 'Notificações',
    descricao: 'Avisos quando seu par mexer no espaço de vocês.',
    ativadas: 'Notificações ativadas 💜',
    desativadas: 'Notificações desativadas.',
    tipos: {
      comentarios: 'Comentários',
      publicacoes: 'Publicações',
      curtidas: 'Curtidas',
      memorias: 'Memórias',
      listas: 'Filmes na lista',
      casal: 'Casal',
    },
    precisaInstalarIos: 'Instale o Mozii na tela inicial para ativar as notificações.',
    indisponivel: 'Este navegador não suporta notificações.',
    semChave: 'O push ainda não foi configurado neste ambiente.',
    permissoesTitulo: 'Permissões do aparelho',
    permissaoNotificacoes: 'Notificações',
    permissaoCameraFotos: 'Câmera e fotos',
    estadoConcedida: 'concedida neste aparelho',
    estadoNegada: 'negada neste aparelho',
    estadoNaoPedida: 'ainda não pedida',
    cameraGerenciadaPeloSistema: 'o sistema pede na hora de usar',
    dicaReativar:
      'Negou sem querer? Reative em Ajustes › Notificações › Mozii (iPhone) ou nas permissões do site (Android).',
    conviteTitulo: 'Quer saber quando seu par publicar?',
    conviteDescricao: 'Ative as notificações — dá para escolher o quê.',
    conviteAtivar: 'Ativar notificações',
    conviteDepois: 'Agora não',
  },

  atualizacao: {
    disponivel: 'Nova versão do Mozii disponível!',
    atualizar: 'Atualizar',
  },

  configuracao: {
    titulo: 'Falta configurar o ambiente',
    explicacao:
      'Copie o arquivo .env.example para .env.local e preencha as chaves do Supabase e do TMDB. Depois reinicie o servidor de desenvolvimento.',
    variaveisFaltando: 'Variáveis ausentes:',
  },
} as const
